[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]

[features]
default = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
exclude = ["tests"]
