[package]
name = "rust-os"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0
panic = "abort"
debug = true

[dependencies]
riscv = "0.6.0"

[profile.release]
opt-level = 3
panic = "abort"