[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tsrc/arch/riscv/linker.ld"]
runner = "qemu-system-riscv64 -machine virt -nographic -bios none -kernel"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]